In [1]:
print('Hello Jupyter Notebook!')

Hello Jupyter Notebook!


In [3]:
1+1

2

In [5]:
1e15

1000000000000000.0

In [7]:
1e-5

1e-05

In [9]:
17

17

In [11]:
0b10001

17

In [13]:
0o21

17

In [15]:
0x11

17

In [17]:
bin(17)

'0b10001'

In [19]:
oct(17)

'0o21'

In [21]:
hex(17)

'0x11'

In [23]:
0b10*0o10+0x10-10

22

In [27]:
bin(0b10*0o10+0x10-10)

'0b10110'

In [29]:
oct(0b10*0o10+0x10-10)

'0o26'

In [31]:
hex(0b10*0o10+0x10-10)

'0x16'

In [33]:
print(True)

True


In [35]:
type(True)

bool

In [37]:
print(True and False)

False


In [39]:
print(True or False)
print(not True)

True
False


In [43]:
print(5 ==3)
print(5!=3)
print(5<3)
print(5>3)
print(5<=3)
print(5>=3)

False
True
False
True
False
True


In [45]:
print(1>0 and -2 <0)

True


In [47]:
12340*1/2

6170.0

In [49]:
12340*1/4

3085.0

In [51]:
12340*1/5

2468.0

In [53]:
abc = 12340
print(abc)

12340


In [55]:
abc

12340

In [57]:
print(abc*1/2)

6170.0


In [59]:
print("String Test")

String Test


In [61]:
string1 = "String Test 1" 

In [63]:
print(string1)

String Test 1


In [65]:
string2 =' String Test 2 '
print(string2)

 String Test 2 


In [67]:
type(string1)

str

In [69]:
string3 = 'This is a "double" quotation test'
print(string3)

This is a "double" quotation test


In [71]:
a = 'Enjoy '
b = 'python!'
c = a+b
print(c)

Enjoy python!


In [73]:
print(a *3)

Enjoy Enjoy Enjoy 


In [75]:
student = [90,95,85,80]

In [77]:
student

[90, 95, 85, 80]

In [79]:
type(student)

list

In [83]:
student[0]

90

In [85]:
student[-1]

80

In [87]:
student[1] = 100

In [89]:
student

[90, 100, 85, 80]

In [91]:
myFriends = ['Jamees',' Robert','Lisa','Mary']

In [93]:
myFriends

['Jamees', ' Robert', 'Lisa', 'Mary']

In [95]:
myFriends[2]

'Lisa'

In [97]:
mixedList = [0,2,3.14,'python','program',True, myFriends]
mixedList

[0, 2, 3.14, 'python', 'program', True, ['Jamees', ' Robert', 'Lisa', 'Mary']]

In [99]:
list_con1 = [1,2,3,4]
list_con2 = [5,6,7,8]
list_con = list_con1 + list_con2

In [101]:
print(list_con)

[1, 2, 3, 4, 5, 6, 7, 8]


In [105]:
list_con = list_con*3

In [107]:
print(list_con)

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]


In [109]:
list_data = [0,1,2,3,4,5,6,7,8,9]

In [111]:
print(list_data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [113]:
print(list_data[0:3])

[0, 1, 2]


In [115]:
print(list_data[4:8])

[4, 5, 6, 7]


In [117]:
print(list_data[:3])

[0, 1, 2]


In [121]:
print(list_data[7:])

[7, 8, 9]


In [123]:
print(list_data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [125]:
del list_data[6]

In [127]:
print(list_data)

[0, 1, 2, 3, 4, 5, 7, 8, 9]


In [129]:
list_data1 = [1,2,3,4,5]
print(5 in list_data1)
print(6 in list_data1)

True
False


In [135]:
myFriends = ['James','Robert','Lisa','Mary']
print(myFriends)

['James', 'Robert', 'Lisa', 'Mary']


In [137]:
myFriends.append('Thomas')

In [139]:
print(myFriends)

['James', 'Robert', 'Lisa', 'Mary', 'Thomas']


In [141]:
myFriends.insert(1,'Paul')
print(myFriends)

['James', 'Paul', 'Robert', 'Lisa', 'Mary', 'Thomas']


In [145]:
myFriends.extend(['Laura','Betty'])
print(myFriends)

['James', 'Paul', 'Robert', 'Lisa', 'Mary', 'Thomas', 'Laura', 'Betty']


In [147]:
tuple1 = (1,2,3,4)
tuple

tuple

In [149]:
tuple1

(1, 2, 3, 4)

In [153]:
type(tuple1)

tuple

In [155]:
tuple1[1]

2

In [157]:
tuple2 = 5,6,7,8
print(tuple2)

(5, 6, 7, 8)


In [159]:
type(tuple2)

tuple

In [161]:
tuple3 = (9,)
tuple4 = 10,
print(tuple3)
print(tuple4)


(9,)
(10,)


In [163]:
tuple6=('a','b','c','d','e','f')
tuple6.index('c')

2

In [165]:
tuple7 = ('a','a','a','a','b','b','b','c','c','c')
tuple7.count('a')

4

In [167]:
set1 = {1,2,3}
set1a = {1,2,3,3}
print(set1)
print(set1a)

{1, 2, 3}
{1, 2, 3}


In [169]:
type(set1)

set

In [171]:
A = {1,2,3,4,5}
B = {4,5,6,7,8,9,10}
A.intersection(B)

{4, 5}

In [173]:
A.union(B)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [175]:
A.difference(B)

{1, 2, 3}

In [177]:
A & B

{4, 5}

In [179]:
A | B

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [181]:
A -B 

{1, 2, 3}

In [185]:
a =[1,2,3,4,5]
type(a)

list

In [187]:
b= tuple(a)
b

(1, 2, 3, 4, 5)

In [189]:
type(b)

tuple

In [191]:
c = set(a)
c

{1, 2, 3, 4, 5}

In [193]:
type(c)

set

In [195]:
list(b)

[1, 2, 3, 4, 5]

In [199]:
country_capital = {"영국":"런던", "프랑스":"파리","스위스":"베른","호주":"멜버른","덴마크":"코펜하겐"}
country_capital

{'영국': '런던', '프랑스': '파리', '스위스': '베른', '호주': '멜버른', '덴마크': '코펜하겐'}

In [201]:
type(country_capital)

dict

In [203]:
country_capital["영국"]

'런던'

In [207]:
dict_data1 = {1:"버스",3:"비행기",4:"택시",5:"자전거"}
dict_data1

{1: '버스', 3: '비행기', 4: '택시', 5: '자전거'}

In [209]:
dict_data1[3]

'비행기'

In [211]:
dict_data2 = {1:10, 2:20, 3:30, 4:40, 5:50}
print(dict_data2)
print(dict_data2[4])

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50}
40


In [215]:
dict_data3 = {"list_data1":[11,12,13],"list_data2":[21,22,23]}
print(dict_data3)
print(dict_data3["list_data2"])

{'list_data1': [11, 12, 13], 'list_data2': [21, 22, 23]}
[21, 22, 23]


In [217]:
mixed_dict = {1:10, 'dict_num':{1:10,2:20},"dict_list_tuple":{"A":[11,12,13],"B":(21,22,23)}, "dict_string":"이것은 책입니다."}
mixed_dict

{1: 10,
 'dict_num': {1: 10, 2: 20},
 'dict_list_tuple': {'A': [11, 12, 13], 'B': (21, 22, 23)},
 'dict_string': '이것은 책입니다.'}

In [219]:
country_capital["독일"]="베를린"
country_capital

{'영국': '런던', '프랑스': '파리', '스위스': '베른', '호주': '멜버른', '덴마크': '코펜하겐', '독일': '베를린'}

In [221]:
country_capital["호주"]="캔버라"
country_capital

{'영국': '런던', '프랑스': '파리', '스위스': '베른', '호주': '캔버라', '덴마크': '코펜하겐', '독일': '베를린'}

In [223]:
del country_capital["덴마크"]
country_capital

{'영국': '런던', '프랑스': '파리', '스위스': '베른', '호주': '캔버라', '독일': '베를린'}

In [225]:
fruit_code = {"사과":101, "배":102,"딸기":103,"포도":104,"바나나":105}
print(fruit_code.keys())

dict_keys(['사과', '배', '딸기', '포도', '바나나'])


In [227]:
print(fruit_code.values())

dict_values([101, 102, 103, 104, 105])


In [229]:
print(fruit_code.items())

dict_items([('사과', 101), ('배', 102), ('딸기', 103), ('포도', 104), ('바나나', 105)])


In [231]:
list(fruit_code.keys())

['사과', '배', '딸기', '포도', '바나나']

In [233]:
list(fruit_code.values())

[101, 102, 103, 104, 105]

In [235]:
list(fruit_code.items())

[('사과', 101), ('배', 102), ('딸기', 103), ('포도', 104), ('바나나', 105)]

In [237]:
fruit_code2={"오렌지":106,"수박":107}

In [239]:
fruit_code.update(fruit_code2)

In [241]:
fruit_code

{'사과': 101, '배': 102, '딸기': 103, '포도': 104, '바나나': 105, '오렌지': 106, '수박': 107}

In [243]:
fruit_code2.clear()
print(fruit_code2)
type(fruit_code2)

{}


dict

In [245]:
x = 95
if x > 90:
    print("Pass")

Pass


In [247]:
x = 75 
if x >= 90:
    print("Pass")
else:
    print("Fail")

Fail


In [249]:
x = 100
if x >= 90 : 
    if x == 100 : 
        print("Perfect")
    else: 
        print("Very Good")
elif(x>= 80) and (x < 90):
    print("GOOD")
else:
    print("BAD")
    

Perfect


In [253]:
for a in [0,1,2,3,4,5]:
    print(a)

0
1
2
3
4
5


In [255]:
myFriends = ['James','Robert','Lisa','Mary']
for myFriend in myFriends:
    print(myFriend)

James
Robert
Lisa
Mary


In [259]:
print(range(0,10,1))

range(0, 10)


In [261]:
print(list(range(0,10,1)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [263]:
for a in range(0,6,1):
    print(a)

0
1
2
3
4
5


In [265]:
for a in range(0,6,2):
    print(a)

0
2
4


In [267]:
print(list(range(0,10,1)))
print(list(range(0,10)))
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [271]:
print(list(range(0,20,5)))
print(list(range(-10,0,2)))
print(list(range(3,-10,-3)))
print(list(range(0,-5,1)))


[0, 5, 10, 15]
[-10, -8, -6, -4, -2]
[3, 0, -3, -6, -9]
[]


In [273]:
x_list=['x1','x2']
y_list=['y1','y2']
print("x y")
for x in x_list:
    for y in y_list:
        print(x,y)

x y
x1 y1
x1 y2
x2 y1
x2 y2


In [277]:
names = ['James','Robert','Lisa','Mary']
scores = [95,96,97,94]

for k in range(len(names)):
    print(names[k],scores[k])

James 95
Robert 96
Lisa 97
Mary 94


In [279]:
for name, score in zip(names, scores):
    print(name, score)

James 95
Robert 96
Lisa 97
Mary 94


In [281]:
i=0
sum=0
print("i sum")
while (sum < 20):
    i = i + 1 
    sum = sum + i
    print(i, sum)

i sum
1 1
2 3
3 6
4 10
5 15
6 21


In [283]:
k = 0
while True : 
    k = k +1 
    if(k > 3 ) :
        break
    print(k)

1
2
3


In [285]:
for k in range(10):
    if(k > 2):
        break
    print(k)

0
1
2


In [287]:
for k in range(5):
    if(k==2):
        continue
    print(k)

0
1
3
4


In [289]:
k = 0
while True:
    k = k+1
    if(k==2):
        print("continue next")
        continue
    if(k>4):
        break
    print(k)
    

1
continue next
3
4


In [291]:
numbers = [1,2,3,4,5]
square = []

for i in numbers : 
    square.append(i**2)
print(square)


[1, 4, 9, 16, 25]


In [293]:
numbers = [1,2,3,4,5]
square = [i**2 for i in numbers]
print(square)


[1, 4, 9, 16, 25]


In [299]:
numbers = [1,2,3,4,5]
square = []
for i in numbers : 
    if i >= 3:
        square.append(i**2)
print(square)
    

[9, 16, 25]


In [301]:
numbers = [1,2,3,4,5]
square = [i**2 for i in numbers if i >=3]
print(square)

[9, 16, 25]


In [305]:
print("Hello Python!!")

Hello Python!!


In [307]:
print("Best", "python","book")

Best python book


In [309]:
print("Best","python","book", sep="-:*:-")

Best-:*:-python-:*:-book


In [311]:
print("abcd"+"efg")

abcdefg


In [313]:
print("Best","python","book"+":","this book")

Best python book: this book


In [315]:
x = 10
print(x)

10


In [317]:
name = "james"
ID_num = 789
print("Name:", name + ",","ID Number:", ID_num)

Name: james, ID Number: 789


In [319]:
print("James is my friend. \nHe is Korean.")

James is my friend. 
He is Korean.


In [321]:
print("Welcome to " )

Welcome to 


In [323]:
print("python")

python


In [325]:
print("Welcome to " , end = "")
print("python")

Welcome to python


In [327]:
name = "광재"
print("%s는 나의 친구입니다." % name)

광재는 나의 친구입니다.


In [329]:
r = 3
PI = 3.14159265358979
print("반지름 : %d, 원주율: %f" % (r, PI)) 

반지름 : 3, 원주율: 3.141593


In [331]:
animal_0 = "cat"
animal_1 = "dog"
animal_2 = "fox"
print("Animal: {0}".format(animal_0))
print("Animal: {0},{1},{2}".format(animal_0, animal_1, animal_2))

Animal: cat
Animal: cat,dog,fox


In [333]:
print("Animal : {1},{2},{0}".format(animal_0, animal_1, animal_2))

Animal : dog,fox,cat


In [335]:
print("Animal: {0},{2}".format(animal_0, animal_1, animal_2))

Animal: cat,fox


In [337]:
print("Animal:{},{},{}".format(animal_0, animal_1, animal_2))

Animal:cat,dog,fox


In [339]:
name="Tomas"
age =10
a = 0.1234567890123456789
fmt_string = "String : {0}. Integer Number:{1}.Floating Number:{2}"
print(fmt_string.format(name,age, a))

String : Tomas. Integer Number:10.Floating Number:0.12345678901234568


In [341]:
a = 0.1234567890123456789
print("{0:.2f},{0:.5f}".format(a))

0.12,0.12346


In [343]:
data = input("문자열")

문자열 안녕하신가? 


In [345]:
yourName = input("당신의 이름은?")
print("당신은 {}이군요.".format(yourName))

당신의 이름은? 김요한


당신은 김요한이군요.


In [347]:
num = input("숫자를 입력하세요 : ")
print("당신이 입력한 숫자는 {}입니다.".format(num))

숫자를 입력하세요 :  12


당신이 입력한 숫자는 12입니다.


In [349]:
a = input("정사각형 한변의 길이는?:")
area = int(a)**2
print("정사각형의 넓이 : {}".format(area))

정사각형 한변의 길이는?: 12


정사각형의 넓이 : 144


In [351]:
b = input("정사각형 한변의 길이는 ?:")
area = float(b)**2
print("정사각형의 넓이 : {}".format(area))

정사각형 한변의 길이는 ?: 12


정사각형의 넓이 : 144.0


In [353]:
c = input("정사각형 한변의 길이는?:")
area = float(c)**2
print("정사각형의 넓이 : {}".format(area))

정사각형 한변의 길이는?: 3


정사각형의 넓이 : 9.0


In [359]:

f = open('myFile.txt','w')
f.write('This is my first file.')
f.close()

In [361]:
!type myFile.txt

This is my first file.


In [367]:
f = open('myFile.txt','r') 
file_text = f.read()
f.close()

print(file_text)

This is my first file.


In [369]:
f = open('two_times_table.txt','w')
for num in range(1,6):
    format_string = "2 * {0} = {1}\n".format(num,2*num)
    f.write(format_string)
f.close()

In [371]:
!type two_times_table.txt

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10


In [373]:
f = open("two_times_table.txt")
line1 = f.readline()
line2 = f.readline()
f.close()
print(line1, end="")
print(line2, end="")


2 * 1 = 2
2 * 2 = 4


In [375]:
f = open("two_times_table.txt")
line = f.readline()
while line : 
    print(line, end = "")
    line = f.readline()
f.close()

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10


In [377]:
f = open("two_times_table.txt")
lines = f.readlines()
f.close()
print(lines)

['2 * 1 = 2\n', '2 * 2 = 4\n', '2 * 3 = 6\n', '2 * 4 = 8\n', '2 * 5 = 10\n']


In [379]:
f = open("two_times_table.txt")
lines = f.readlines()
f.close()
print(lines)

['2 * 1 = 2\n', '2 * 2 = 4\n', '2 * 3 = 6\n', '2 * 4 = 8\n', '2 * 5 = 10\n']


In [381]:
f = open("two_times_table.txt")
lines = f.readlines()
f.close()
for line in lines:
    print(line, end="")

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10


In [383]:
f = open("two_times_table.txt")
for line in f.readlines():
    print(line, end="")
    f.close()

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10


In [385]:
f = open("two_times_table.txt")
for line in f:
    print(line, end="")
f.close()


2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10


In [387]:
f = open('myTextFile.txt','w')
f.write('File write/read test.')
f.close()


In [389]:
f = open('myTextFile.txt','r')
test = f.read()
f.close()
print(test)

File write/read test.


In [391]:
with open('C:/Users/user1/git/BOOK_PYTHON_DATA/myTextFile2.txt','w') as f:
    f.write('File read/write test2: line1\n')
    f.write('File read/write test2: line2\n')
    f.write('File read/write test2: line3\n')


In [393]:
with open('C:/Users/user1/git/BOOK_PYTHON_DATA/myTextFile2.txt') as f:
    file_string = f.read()
    print(file_string)

File read/write test2: line1
File read/write test2: line2
File read/write test2: line3



In [395]:
with open('C:/Users/user1/git/BOOK_PYTHON_DATA/myTextFile2.txt','w') as f:
    for num in range(1,6):
        format_string = "3 * {0} = {1}\n".format(num,3*num)
        f.write(format_string)
        

In [397]:
with open('C:/Users/user1/git/BOOK_PYTHON_DATA/myTextFile2.txt','r') as f:
    for line in f:
        print(line, end="")

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15


In [399]:
def my_func():
    print("My first function!")
    print("This is a function.")

In [401]:
my_func()

My first function!
This is a function.


In [403]:
def my_friend(friendName):
    print("{}는 나의 친구입니다.".format(friendName))

In [405]:
my_friend("철수")
my_friend("영미")

철수는 나의 친구입니다.
영미는 나의 친구입니다.


In [409]:
def my_student_info(name, school_ID, phoneNumber):
    print("--------------------")
    print("-학생이름:",name)
    print("-학급번호:", school_ID)
    print("-전화번호:", phoneNumber)

In [411]:
my_student_info("현아","01","01-235-6789")
my_student_info("진수","02","01-987-6543")

--------------------
-학생이름: 현아
-학급번호: 01
-전화번호: 01-235-6789
--------------------
-학생이름: 진수
-학급번호: 02
-전화번호: 01-987-6543


In [413]:
def my_student_info(name, school_ID, phoneNumber):
    print("****************")
    print("*학생이름:",name)
    print("*학급번호:", school_ID)
    print("*전화번호:",phoneNumber)
    

In [417]:
my_student_info("현아","01","01-235-6789")
my_student_info("진수","02","01-987-6543")

****************
*학생이름: 현아
*학급번호: 01
*전화번호: 01-235-6789
****************
*학생이름: 진수
*학급번호: 02
*전화번호: 01-987-6543


In [421]:
def my_calc(x,y):
    z = x*y
    return z
    

In [423]:
my_calc(3,4)

12

In [437]:
def my_student_info_list(student_info):
    print("**************")
    print("*학생이름:",student_info[0])
    print("*학급번호:",student_info[1])
    print("*전화번호:",student_info[2])
    print("**************")
    

In [439]:
student1_info = ["현아","01","01-235-6789"]
my_student_info_list(student1_info)

**************
*학생이름: 현아
*학급번호: 01
*전화번호: 01-235-6789
**************


In [441]:
my_student_info_list(["진수","02","01-987-6543"])

**************
*학생이름: 진수
*학급번호: 02
*전화번호: 01-987-6543
**************


In [455]:
a = 5
def func1():
    a = 1
    print("[func1] 지역변수 a =",a)

In [445]:
def func2():
    a = 2
    print("[func2] 지역변수 a= ",a)
    

In [447]:
def func3():
    print("[func3] 전역변수 a = ", a)
    

In [449]:
def func4():
    global a 
    a = 4
    print("[func4] 전역변수 a = ",a)
    

In [457]:
func1()
func2()
print("전역변수 a = " , a)

[func1] 지역변수 a = 1
[func2] 지역변수 a=  2
전역변수 a =  5


In [459]:
func3()
func4()
func3()

[func3] 전역변수 a =  5
[func4] 전역변수 a =  4
[func3] 전역변수 a =  4


In [461]:
(lambda x : x**2) (3)

9

In [463]:
mySquare = lambda x  : x**2
mySquare(2)

4

In [465]:
mySquare(5)

25

In [467]:
mySimpleFunc = lambda x,y,z : 2*x + 3*y + z
mySimpleFunc(1,2,3)

11

In [469]:
[int(0.123), int(3.5123456), int(-1.312367)]

[0, 3, -1]

In [471]:
[int('123'), int('5678'),int('-9012')]

[123, 5678, -9012]

In [473]:
[float(0), float(123), float(-567)]

[0.0, 123.0, -567.0]

In [475]:
[float('10'), float('0.123'),float('-567.89')]

[10.0, 0.123, -567.89]

In [477]:
[str(123),str(459678),str(-987)]

['123', '459678', '-987']

In [479]:
[str(0.213), str(345.678),str(-5.987)]

['0.213', '345.678', '-5.987']

In [481]:
list_data = ['abc',1,2,'def']

In [485]:
tuple_data=('abc',1,2,'def')
set_data = {'abc',1,2,'def'}


In [487]:
[type(list_data),type(tuple_data), type(set_data)]

[list, tuple, set]

In [489]:
print("리스트 변환:" , list(tuple_data), list(set_data))

리스트 변환: ['abc', 1, 2, 'def'] ['def', 1, 2, 'abc']


In [493]:
print("튜플로 변환 :", tuple(list_data), tuple(set_data))

튜플로 변환 : ('abc', 1, 2, 'def') ('def', 1, 2, 'abc')


In [495]:
print("세트로 변환:", set(list_data), set(tuple_data))

세트로 변환: {'def', 1, 2, 'abc'} {'def', 1, 2, 'abc'}


In [497]:
bool('a')

True

In [499]:
bool('')

False

In [501]:
bool(None)

False

In [503]:
bool(1)


True

In [505]:
myFriends =[]

In [507]:
bool(myFriends)

False

In [509]:
myFriends = ['James','Robert','Lisa','Mary']
bool(myFriends)

True

In [511]:
myNum=()
bool(myNum)

False

In [513]:
myNum =(1,2,3)
bool(myNum)

True

In [515]:
mySetA ={}
bool(mySetA)

False

In [517]:
mySetA = {10,20,30}
bool(mySetA)

True

In [521]:
def print_name(name):
    if bool(name):
        print("입력된 이름 : ", name)
    else : 
        print("입력된 이름이 없습니다.")

In [523]:
print_name("James")

입력된 이름 :  James


In [525]:
print_name("")

입력된 이름이 없습니다.


In [529]:
myNum = [10,5,12,0,3.5,99.5,42]

In [531]:
[min(myNum),max(myNum)]

[0, 99.5]

In [533]:
myStr = 'zxyabc'
[min(myStr),max(myStr)]

['a', 'z']

In [535]:
myNum = (10,5,12,0,3.5, 99.5,42)
[min(myNum),max(myNum)]

[0, 99.5]

In [537]:
myNum = {"Abc","abc","bcd","efg"}
[min(myNum), max(myNum)]

['Abc', 'efg']

In [541]:
[abs(10), abs(-10)]

[10, 10]

In [543]:
[abs(2.45), abs(-2.45)]

[2.45, 2.45]

In [551]:
del sum
sumList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
sum(sumList)

55

In [553]:
len("ab cd")


5

In [555]:
len([1,2,3,4,5,6,7,8])

8

In [557]:
len((1,2,3,4,5))

5

In [559]:
len({'a','b','c','d'})

4

In [561]:
len({1:"Thomas",2:"Edward", 3:"Henry"})

3

In [563]:
scores = [90,80,95,85]

In [565]:
score_sum = 0
subject_num = 0
for score in scores:
    score_sum = score_sum +score
    subject_num = subject_num +1 
average = score_sum / subject_num 
print("총점 : {0}, 평균:{1}".format(score_sum, average))


총점 : 350, 평균:87.5


In [571]:
scores = [90,80,95,85]
print("총점 :{0}, 평균:{1}".format(sum(scores), sum(scores)/len(scores)))

총점 :350, 평균:87.5


In [573]:
print("최하 점스 : {0}, 최고 점수 :{1}".format(min(scores), max(scores)))

최하 점스 : 80, 최고 점수 :95


In [36]:
class Bicycle():
    def __init__(self, wheel_size, color):
        self.wheel_size = wheel_size
        self.color = color
        
    def move(self, speed):
        print("자전거: 시속 {0}킬로미터로 전진".format(speed))

    def turn(self, direction):
        print("자전거 : {0}회전".format(direction))

    def stop(self):
        print("자전거{0},{1}): 정지".format(self.wheel_size, self.color))

In [4]:
my_bicycle = Bicycle()

In [6]:
my_bicycle

In [38]:
my_bicycle = Bicycle(26, 'black')

my_bicycle.move(30)
my_bicycle.turn('좌')
my_bicycle.stop()


자전거: 시속 30킬로미터로 전진
자전거 : 좌회전
자전거26,black): 정지


In [10]:
print("바퀴 크기:", my_bicycle.wheel_size)
print("색상:", my_bicycle.color)

바퀴 크기: 26
색상: black


In [32]:
bicycle1 = Bicycle()

bicycle1.wheel_size = 27
bicycle1.color = 'red'
bicycle1.move(20)
bicycle1.turn('좌')
bicycle1.stop()

자전거: 시속 20킬로미터로 전진
자전거 : 좌회전
자전거27,red): 정지


In [34]:
bicycle2 = Bicycle()
bicycle2.wheel_size = 24
bicycle2.color = 'blue'
bicycle2.move(15)
bicycle2.turn('우')
bicycle2.stop()

자전거: 시속 15킬로미터로 전진
자전거 : 우회전
자전거24,blue): 정지


In [42]:
class Car():
    instance_count = 0 # 공통으로 사용
    def __init__(self, size, color):
        self.size = size
        self.color = color
        Car.instance_count = Car.instance_count +1
        print("자동차 객체의 수 : {0}".format(Car.instance_count))
    def move(self):
            print("자동차({0}&{1})가 움직입니다.".format(self.size, self.color))

In [44]:
car1 = Car('smal','white')
car2 = Car('big','black')

자동차 객체의 수 : 1
자동차 객체의 수 : 2


In [46]:
print("Car 클래스의 총 인스턴스 개수 :{}".format(Car.instance_count))

Car 클래스의 총 인스턴스 개수 :2


In [48]:
print("Car 클래스의 총 인스턴스 개수:{}".format(car1.instance_count))
print("Car 클래스의 총 인스턴스 개수 :{}".format(car2.instance_count))

Car 클래스의 총 인스턴스 개수:2
Car 클래스의 총 인스턴스 개수 :2


In [50]:
car1.move()
car2.move()

자동차(smal&white)가 움직입니다.
자동차(big&black)가 움직입니다.


In [54]:
class Car2():
    count = 0

    def __init__(self, size, num):
        self.size = size
        self.count = num
        Car2.count = Car2.count +1
        print("자동차 객체의 수 : Car2.count ={0}".format(Car2.count))
        print("인스턴스 변수 초기화 : self.count = {0}".format(self.count))

    def move(self):
        print("자동차({0} & {1}가 움직입니다.".format(self.size, self.count))

In [56]:
car1 = Car2("big",20)
car2 = Car2("small",30)

자동차 객체의 수 : Car2.count =1
인스턴스 변수 초기화 : self.count = 20
자동차 객체의 수 : Car2.count =2
인스턴스 변수 초기화 : self.count = 30


In [58]:
# 인스턴스 메서드는 각 객체에서 개별적으로 동작하는 함수를 만들고자 할때 사용하는 함수
class Car():
    instance_count = 0
    def __init__(self,size, color):
        self.size =size
        self.color = color
        Car.instance_count = Car.instance_count +1 
        print("자동차 객체의 수 :{0}".format(Car.instance_count))
    def move(self, speed):
        self.speed = speed
        print("자동차({0} & {1})가 ".format(self.size, self.color),end='')
        print("시속 {0}킬로미터로 전진".format(self.speed))
    def auto_cruise(self):
        print("자율 주행 모드")
        self.move(self.speed)

In [60]:
car1 = Car("small","red")
car2 = Car("big","green")
car1.move(80)
car2.move(100)
car1.auto_cruise()
car2.auto_cruise()

자동차 객체의 수 :1
자동차 객체의 수 :2
자동차(small & red)가 시속 80킬로미터로 전진
자동차(big & green)가 시속 100킬로미터로 전진
자율 주행 모드
자동차(small & red)가 시속 80킬로미터로 전진
자율 주행 모드
자동차(big & green)가 시속 100킬로미터로 전진


In [65]:
# 정적 메서드는 클래스와 관련이 있어서 클래스 안에 두기는 하지만 클래스나 클래스의 인스턴스(객체)와는 무관하게 독립적으로 동작하는 함수를 만들고 싶을 때 이용하는 함수입니다.
# @staticmethod를 선언해 정적 메서드임을 표시합니다.
class Car():
    instance_count = 0
    def __init__(self,size, color):
        self.size =size
        self.color = color
        Car.instance_count = Car.instance_count +1 
        print("자동차 객체의 수 :{0}".format(Car.instance_count))
        
    def move(self, speed):
        self.speed = speed
        print("자동차({0} & {1})가 ".format(self.size, self.color),end='')
        print("시속 {0}킬로미터로 전진".format(self.speed))
    def auto_cruise(self):
        print("자율 주행 모드")
        self.move(self.speed)
    @staticmethod
    def check_type(model_code):
        if(model_code >=20):
            print("이 자동차는 전기차입니다.")
        elif(10<=model_code<20):
            print("이 자동차는 가솔린차입니다.")
        else:
            print("이 자동차는 디젤차입니다.")
            

In [67]:
Car.check_type(25)
Car.check_type(2)

이 자동차는 전기차입니다.
이 자동차는 디젤차입니다.


In [69]:
# 클래스 메서드는 클래스 변스를 사용하기 위한 함수 @classmethod를 지정해야함
class Car():
    instance_count = 0
    def __init__(self,size, color):
        self.size =size
        self.color = color
        Car.instance_count = Car.instance_count +1 
       
        
    def move(self, speed):
        self.speed = speed
        print("자동차({0} & {1})가 ".format(self.size, self.color),end='')
        print("시속 {0}킬로미터로 전진".format(self.speed))
    def auto_cruise(self):
        print("자율 주행 모드")
        self.move(self.speed)
    @staticmethod
    def check_type(model_code):
        if(model_code >=20):
            print("이 자동차는 전기차입니다.")
        elif(10<=model_code<20):
            print("이 자동차는 가솔린차입니다.")
        else:
            print("이 자동차는 디젤차입니다.")
    @classmethod
    def count_instance(cls):
        print("자동차 객체의 개수 : {0}".format(cls.instance_count))

In [71]:
Car.count_instance()

car1 = Car("small:","red")
Car.count_instance()
car2 = Car("big","green")
Car.count_instance()


자동차 객체의 개수 : 0
자동차 객체의 개수 : 1
자동차 객체의 개수 : 2


In [79]:
robot1_name = 'R1'
robot1_pos = 0

def robot1_move():
    global robot_pos
    robot_pos = robot_pos +1
    print("{0} position:{1}".format(robot_name, robot_pos))
    
robot2_name = 'R2'
robot2_pos = 10

def robot2_move():
    global robot2_pos
    robot2_pos = robot2_pos +1
    print("{0} position: {1}".format(robot2_name, robot2_pos))

In [81]:
robot1_move()
robot2_move()

R1 position:1
R2 position: 11


In [83]:
class Robot():
    def __init__(self, name, pos):
        self.name = name
        self.pos = pos
    def move(self):
        self.pos = self.pos+1
        print("{0} position:{1}".format(self.name, self.pos))

In [85]:
robot1 = Robot('R1',0)
robot2 = Robot('R2',10)


In [87]:
robot1.move()
robot2.move()

R1 position:1
R2 position:11


In [89]:
myRobot3 = Robot('R3',30)
myRobot4 = Robot('R4',40)
myRobot3.move()
myRobot4.move()

R3 position:31
R4 position:41


In [91]:
class Bicycle():
    def __init__(self, wheel_size, color):
        self.wheel_size = wheel_size
        self.color = color
    def move(self, speed):
        print("자전거: 시속 {0}킬로미터로 전진".format(speed))
    def turn (self, direction):
        print("자전거: {0}회전".format(direction))
    def stop(self):
        print("자전거({0},{1}): 정지 ".format(self.wheel_size, self.color))
        

In [97]:
class FoldingBicycle(Bicycle):
    def __init__(self, wheel_size, color, state):
        Bicycle.__init__(self, wheel_size, color)
        #super().__init__(wheel_size, color) # super()도 사용 가능
        self.state = state
    def fold(self):
        self.state = 'folding'
        print("자전거: 접기, state ={0}".format(self.state))
    def unfold(self):
        self.state = 'unfolding'
        print("자전거: 펴기, state = {0}".format(self.state))

In [99]:
folding_bicycle = FoldingBicycle(27, 'white','unfolding')
folding_bicycle.move(20)
folding_bicycle.fold()
folding_bicycle.unfold()

자전거: 시속 20킬로미터로 전진
자전거: 접기, state =folding
자전거: 펴기, state = unfolding


In [101]:
coffee_menu_str = "에스프레소,아메리카노,카페라떼,카푸치노"
coffee_menu_str.split(',')

['에스프레소', '아메리카노', '카페라떼', '카푸치노']

In [103]:
"에스프레소,아메리카노,카페라테,카푸치노".split(',')

['에스프레소', '아메리카노', '카페라테', '카푸치노']

In [105]:
"에스프레소 아메리카노 카페라떼 카푸치노".split(' ')

['에스프레소', '아메리카노', '카페라떼', '카푸치노']

In [107]:
"에스프레소 아메리카노 카페라떼 카푸치노".split()

['에스프레소', '아메리카노', '카페라떼', '카푸치노']

In [109]:
"  에스프레소 \n\n 아메리카노 \n 카페라떼 카푸치노 \n\n".split()

['에스프레소', '아메리카노', '카페라떼', '카푸치노']

In [111]:
"에스프레소 아메리카노 카페라떼 카푸치노".split(maxsplit=2)

['에스프레소', '아메리카노', '카페라떼 카푸치노']

In [113]:
phone_number = "+82-01-2345-6789"

In [115]:
split_num = phone_number.split("-",1)

In [117]:
print(split_num)
print("국내전화번호: {0}".format(split_num[1]))

['+82', '01-2345-6789']
국내전화번호: 01-2345-6789


In [119]:
"aaaaPythonaaaa".strip('a')

'Python'

In [121]:
test_str ="aaabbPythonbbbbaaa"
temp1 = test_str.strip('a')
temp1

'bbPythonbbbb'

In [123]:
temp1.strip('b')

'Python'

In [125]:
test_str.strip('ab')

'Python'

In [127]:
test_str.strip('ba')

'Python'

In [144]:
test_str_multi = "##***!!!##.... Python is powerful..!!!...%%!#.. "
test_str_multi.strip('*.#!%')

' Python is powerful..!!!...%%!#.. '

In [146]:
test_str_multi.strip('%*!#.')

' Python is powerful..!!!...%%!#.. '

In [148]:
str_lr = "000Python is easy to learn.000"

In [152]:
print(str_lr.strip('0'))
print(str_lr.lstrip('0'))
print(str_lr.rstrip('0'))

Python is easy to learn.
Python is easy to learn.000
000Python is easy to learn.


In [156]:
coffee_menu = " 에스프레소, 아메리카노, 카페라테,   카푸치노 "
coffee_menu_list = coffee_menu.split(',')
coffee_menu_list

[' 에스프레소', ' 아메리카노', ' 카페라테', '   카푸치노 ']

In [158]:
coffee_list = []
for coffee in coffee_menu_list:
    temp = coffee.strip()
    coffee_list.append(temp)
print(coffee_list)

['에스프레소', '아메리카노', '카페라테', '카푸치노']


In [160]:
name1 ="철수"
name2 = "영미"
hello = "님, 주소와 전화 번호를 입력해주세요"
print(name1 + hello)
print(name2 + hello)

철수님, 주소와 전화 번호를 입력해주세요
영미님, 주소와 전화 번호를 입력해주세요


In [162]:
address_list=["서울시","서초구","반포대로","201(반포동)"]
address_list
a=" "
a.join(address_list)

'서울시 서초구 반포대로 201(반포동)'

In [164]:
" ".join(address_list)

'서울시 서초구 반포대로 201(반포동)'

In [166]:
"*^^*".join(address_list)

'서울시*^^*서초구*^^*반포대로*^^*201(반포동)'

In [170]:
str_f = "Python code."
print("찾는 문자열의 위치:",str_f.find("Python"))
print("찾는 문자열의 위치:",str_f.find("code"))
print("찾는 문자열의 위치:",str_f.find("n"))
print("찾는 문자열의 위치:",str_f.find("easy"))

찾는 문자열의 위치: 0
찾는 문자열의 위치: 7
찾는 문자열의 위치: 5
찾는 문자열의 위치: -1


In [172]:
str_f_se = "Python is powerful. Python is easy to learn"
print(str_f_se.find("Python", 10, 30))
print(str_f_se.find("Python",35))

20
-1


In [176]:
str_c = "Python is powerful. Python is easy to learn. Python is open."

print("Python의 개수는 ?: " , str_c.count("Python"))
print("powerful의 개수는 ? :" , str_c.count("powerful"))
print("IPython의 개수는 ? :", str_c.count("IPython"))

Python의 개수는 ?:  3
powerful의 개수는 ? : 1
IPython의 개수는 ? : 0


In [182]:
str_se = "Python is powerful. Python is easy to learn."
print("Python으로 시작? :", str_se.startswith("Python"))
print("is로 시작? : ",str_se.startswith("is"))
print(".로 끝?:", str_se.endswith("."))
print("learn으로 끝?:", str_se.endswith("learn"))


Python으로 시작? : True
is로 시작? :  False
.로 끝?: True
learn으로 끝?: False


In [184]:
str_a = 'Python is fast. Python is friendly. Python is open.'
print(str_a.replace('Python', 'IPython'))
print(str_a.replace('Python','IPython',2))

IPython is fast. IPython is friendly. IPython is open.
IPython is fast. IPython is friendly. Python is open.


In [188]:
str_b = '[Python][is][fast]'
str_b1 = str_b.replace('[','')
str_b2 = str_b1.replace(']','')
print(str_b)
print(str_b1)
print(str_b2)

[Python][is][fast]
Python]is]fast]
Pythonisfast


In [190]:
print('Python'.isalpha())

True


In [192]:
print('Ver. 3.x'.isalpha())

False


In [194]:
print('12345'.isdigit())

True


In [198]:
print('12345abc'.isdigit())

False


In [200]:
print('abc1234'.isalnum())

True


In [202]:
print('   abc1234'.isalnum())

False


In [204]:
print(' '.isspace())

True


In [206]:
print(' 1'.isspace())

False


In [210]:
print('PYTHON'.isupper())
print('Python'.isupper())
print('python'.islower())
print('Python'.islower())

True
False
True
False


In [214]:
string1 = 'Python is powerful. PYTHON IS EASY TO LEARN.'
print(string1.lower())
print(string1.upper())

python is powerful. python is easy to learn.
PYTHON IS POWERFUL. PYTHON IS EASY TO LEARN.


In [216]:
'Python' == 'python'

False

In [218]:
print('Python'.lower() =='python'.lower())
print('Python'.upper() =='python'.upper())

True
True


In [238]:
with open('C:/Users/user1/git/BOOK_PYTHON_DATA/coffeeShopSales.txt','w',encoding='utf-8')as file:
    file.write('날짜 에스프레소 아메리카노 카페라테 카푸치노\n')
    file.write('10.15 10 50 45 20\n')
    file.write('10.16 12 45 41 18\n')
    file.write('10.17 11 53 32 25\n')
    file.write('10.18 15 49 38 22\n')


In [240]:
# 파일을 읽고 내용을 출력하기
with open('C:/Users/user1/git/BOOK_PYTHON_DATA/coffeeShopSales.txt', 'r', encoding='utf-8') as file:
    content = file.read()
    print(content)


날짜 에스프레소 아메리카노 카페라테 카푸치노
10.15 10 50 45 20
10.16 12 45 41 18
10.17 11 53 32 25
10.18 15 49 38 22



In [244]:
file_name = 'C:/Users/user1/git/BOOK_PYTHON_DATA/coffeeShopSales.txt'
with open(file_name, 'r', encoding='utf-8')as f:
    
    for line in f:
        print(line, end='')
    f.close()
    

날짜 에스프레소 아메리카노 카페라테 카푸치노
10.15 10 50 45 20
10.16 12 45 41 18
10.17 11 53 32 25
10.18 15 49 38 22


In [248]:
f = open(file_name, encoding='utf-8')
header = f.readline()
f.close()
header

'날짜 에스프레소 아메리카노 카페라테 카푸치노\n'

In [250]:
header_list = header.split()

In [252]:
header_list

['날짜', '에스프레소', '아메리카노', '카페라테', '카푸치노']

In [254]:
f = open(file_name, encoding='utf-8')
header = f.readline() #f.readline()을 호출하면 첫 번째 줄을 읽은 뒤, 파일의 파일 포인터가 두 번째 줄로 이동합니다.
header_list = header.split()
for line in f: 
    data_list = line.split() 
    print(data_list)
f.close()

['10.15', '10', '50', '45', '20']
['10.16', '12', '45', '41', '18']
['10.17', '11', '53', '32', '25']
['10.18', '15', '49', '38', '22']


In [262]:
f = open(file_name, encoding='utf-8')
header = f.readline()
headerList = header.split()

espresso = []
americano = []
cafelatte = []
cappucino = []

for line in f : 
    dataList = line.split()

    espresso.append(int(dataList[1]))
    americano.append(int(dataList[2]))
    cafelatte.append(int(dataList[3]))
    cappucino.append(int(dataList[4]))
f.close()

print("{0}: {1}".format(headerList[1], espresso))
print("{0}: {1}".format(headerList[2], americano))
print("{0}: {1}".format(headerList[3], cafelatte))
print("{0}: {1}".format(headerList[4], cappucino))

에스프레소: [10, 12, 11, 15]
아메리카노: [50, 45, 53, 49]
카페라테: [45, 41, 32, 38]
카푸치노: [20, 18, 25, 22]


In [264]:
total_sum =[sum(espresso), sum(americano),sum(cafelatte), sum(cappucino)]
total_mean = [sum(espresso)/len(espresso), sum(americano)/len(americano), sum(cafelatte)/len(cafelatte), sum(cappucino)/len(cappucino)]
for k in range(len(total_sum)):
    print('[{0}] 판매량'.format(headerList[k+1]))
    print('-나흘 전체 : {0}, 하루 평균 : {1}'.format(total_sum[k], total_mean[k]))

[에스프레소] 판매량
-나흘 전체 : 48, 하루 평균 : 12.0
[아메리카노] 판매량
-나흘 전체 : 197, 하루 평균 : 49.25
[카페라테] 판매량
-나흘 전체 : 156, 하루 평균 : 39.0
[카푸치노] 판매량
-나흘 전체 : 85, 하루 평균 : 21.25


In [266]:
%%writefile C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_first_module.py
def my_function():
    print("This is my first module.")

Writing C:\Users\user1\git\BOOK_PYTHON_DATA\my_first_module.py


In [286]:
!type C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_first_module.py

def my_function():
    print("This is my first module.")


In [290]:
cd C:\Users\user1\git\BOOK_PYTHON_DATA\modules

C:\Users\user1\git\BOOK_PYTHON_DATA\modules


In [5]:
!echo %PYTHONPATH%

C:\Users\user1\git\BOOK_PYTHON_DATA\modules;C:\Users\user1\git\BOOK_PYTHON_DATA\packages


In [296]:
%%writefile C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_area.py

PI = 3.14
def square_area(a):
    return a ** 2
def circle_area(r):
    return PI*r**2

Writing C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_area.py


In [298]:
cd C:\Users\user1\git\BOOK_PYTHON_DATA

C:\Users\user1\git\BOOK_PYTHON_DATA


In [7]:
import my_area

print('pi =', my_area.PI)
print('square area =', my_area.square_area(5))
print('circle area =', my_area.circle_area(2))

pi = 3.14
square area = 25
circle area = 12.56


In [9]:
dir(my_area)

['PI',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'circle_area',
 'square_area']

In [11]:
from my_area import PI
print('pi=', PI)

pi= 3.14


In [13]:
from my_area import square_area
from my_area import circle_area

print('square area=', square_area(5))
print('circle area=', circle_area(2))

square area= 25
circle area= 12.56


In [17]:
from my_area import PI, square_area, circle_area

print('pi=', PI)
print('square area=', square_area(5))
print('circle area=', circle_area(2))

pi= 3.14
square area= 25
circle area= 12.56


In [19]:
%%writefile C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_module1.py

def func1():
    print("func1 in my_module1")
def func2():
    print("func2 in my_module1")

Writing C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_module1.py


In [21]:
%%writefile C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_module2.py

def func2():
    print("func2 in my_module2")
def func3():
    print("func3 in my_module2")

Writing C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_module2.py


In [23]:
from my_module1 import *
from my_module2 import *

func1()
func2()
func3()

func1 in my_module1
func2 in my_module2
func3 in my_module2


In [27]:
from my_module2 import *
from my_module1 import *

func1()
func2()
func3()

func1 in my_module1
func2 in my_module1
func3 in my_module2


In [29]:
import my_area as area

print('pi=', area.PI)
print('square area=', area.square_area(5))
print('circle area=',area.circle_area(2))


pi= 3.14
square area= 25
circle area= 12.56


In [31]:
from my_area import PI as pi
from my_area import square_area as square
from my_area import circle_area as circle

print('pi=', pi)
print('square area =', square(5))
print('circle area =', circle(2))

pi= 3.14
square area = 25
circle area = 12.56


In [33]:
%%writefile C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_module_test1.py

def func(a):
    print("입력 숫자:",a)
func(3)

Writing C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_module_test1.py


In [35]:
%run C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_module_test1.py

입력 숫자: 3


In [37]:
import my_module_test1

입력 숫자: 3


In [43]:
%%writefile C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_module_test2.py

def func(a):
    print("입력 숫자 : ", a)
if __name__ == "__main__":
    print("모듈을 직접 실행")
    func(3)
    func(4)

Overwriting C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_module_test2.py


In [45]:
%run C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_module_test2.py

모듈을 직접 실행
입력 숫자 :  3
입력 숫자 :  4


In [47]:
import my_module_test2

In [49]:
%%writefile C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_module_test3.py

def func(a):
    print("입력숫자:",a)

if __name__ == "__main__":
    print("모듈을 직접 실행")
    func(3)
    func(4)
else:
    print("모듈을 임포트해서 실행")
    

Writing C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_module_test3.py


In [51]:
%run C:\Users\user1\git\BOOK_PYTHON_DATA\modules\my_module_test3.py

모듈을 직접 실행
입력숫자: 3
입력숫자: 4


In [53]:
import my_module_test3

모듈을 임포트해서 실행


In [55]:
import random
random.random()

0.7733319019176494

In [63]:
import random

dice1 = random.randint(1,6)
dice2 = random.randint(1,6)

print('주사위 두개의 숫자 : {0}, {1}'.format(dice1, dice2))

주사위 두개의 숫자 : 4, 2


In [65]:
import random

random.randrange(0,11,2)

10

In [67]:
import random

num1 = random.randrange(1,10,2)
num2 = random.randrange(0,100,10)
print('num1: {0}, num2: {1}'.format(num1,num2))

num1: 7, num2: 50


In [69]:
import random

menu = ['비빔밥','된장찌개','볶음밥','불고기','스파게티','피자','탕수육']
random.choice(menu)

'비빔밥'

In [71]:
import random
random.sample([1,2,3,4,5],2)

[4, 1]

In [73]:
import datetime

set_day = datetime.date(2019,3,1)
print(set_day)

2019-03-01


In [75]:
print('{0}/{1}/{2}'.format(set_day.year, set_day.month, set_day.day))

2019/3/1


In [77]:
import datetime

day1 = datetime.date(2019,4,1)
day2 = datetime.date(2019,7,10)

In [79]:
diff_day = day2 - day1
print(diff_day)

100 days, 0:00:00


In [81]:
type(day1)

datetime.date

In [85]:
type(diff_day)

datetime.timedelta

In [87]:
print("** 지정된 두 날짜의 차이는 {}일입니다. **".format(diff_day.days))

** 지정된 두 날짜의 차이는 100일입니다. **


In [89]:
import datetime

print(datetime.date.today())

2025-03-06


In [93]:
import datetime

today = datetime.date.today()
special_day = datetime.date(2025,12,31)
print(special_day - today)

300 days, 0:00:00


In [95]:
import datetime

set_time = datetime.time(15,30,45)
print(set_time)

15:30:45


In [97]:
print('{0}:{1}:{2}'.format(set_time.hour, set_time.minute,set_time.second))

15:30:45


In [99]:
import datetime

set_dt = datetime.datetime(2018,10,9,10,20,0)
print(set_dt)

2018-10-09 10:20:00


In [103]:
print('날짜 {0}/{1}/{2}'.format(set_dt.year, set_dt.month, set_dt.day))
print('시각 {0}:{1}:{2}'.format(set_dt.hour, set_dt.minute, set_dt.second))

날짜 2018/10/9
시각 10:20:0


In [105]:
import datetime

now = datetime.datetime.now()
print(now)

2025-03-06 15:36:19.171934


In [107]:
print("Date & Time: {:%Y-%m-%d, %H:%M:%S}".format(now))

Date & Time: 2025-03-06, 15:36:19


In [109]:
import calendar

print(calendar.calendar(2025))

                                  2025

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2                      1  2
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       3  4  5  6  7  8  9
13 14 15 16 17 18 19      10 11 12 13 14 15 16      10 11 12 13 14 15 16
20 21 22 23 24 25 26      17 18 19 20 21 22 23      17 18 19 20 21 22 23
27 28 29 30 31            24 25 26 27 28            24 25 26 27 28 29 30
                                                    31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                1  2  3  4                         1
 7  8  9 10 11 12 13       5  6  7  8  9 10 11       2  3  4  5  6  7  8
14 15 16 17 18 19 20      12 13 14 15 16 17 18       9 10 11 12 13 14 15
21 22 23 24 25 26 27      19 20 21 22 23 24 

In [111]:
print(calendar.month(2025,3))

     March 2025
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
31



In [113]:
calendar.monthrange(2025,3)

(calendar.SATURDAY, 31)

In [115]:
calendar.setfirstweekday(calendar.SUNDAY)
print(calendar.month(2025,3))

     March 2025
Su Mo Tu We Th Fr Sa
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30 31



In [117]:
print(calendar.weekday(2025,3,6))


3


In [119]:
print(calendar.isleap(2025))

False


In [123]:
print(calendar.isleap(2024))

True


In [127]:
mkdir C:\Users\user1\git\BOOK_PYTHON_DATA\packages\image; C:\Users\user1\git\BOOK_PYTHON_DATA\packages\image\io_file

In [129]:
%%writefile C:\Users\user1\git\BOOK_PYTHON_DATA\packages\image\__init__.py
# File name : __init__.py

Writing C:\Users\user1\git\BOOK_PYTHON_DATA\packages\image\__init__.py


In [133]:
%%writefile C:\Users\user1\git\BOOK_PYTHON_DATA\packages\image\io_file\__init__.py
# File name : __init__.py

Writing C:\Users\user1\git\BOOK_PYTHON_DATA\packages\image\io_file\__init__.py


In [186]:
%%writefile C:\Users\user1\git\BOOK_PYTHON_DATA\packages\image\io_file\imgread.py
# File name : imgread.py

def pngread():
    print("pngread in ingread module")

def jpgread():
    print("jpgread in imgread module")

Writing C:\Users\user1\git\BOOK_PYTHON_DATA\packages\image\io_file\imgread.py


In [3]:
!tree /F C:\Users\user1\git\BOOK_PYTHON_DATA\packages

OS 볼륨에 대한 폴더 경로의 목록입니다.
볼륨 일련 번호가 000000CE 7EBF:7429입니다.
C:\USERS\USER1\GIT\BOOK_PYTHON_DATA\PACKAGES
└─image
    │  __init__.py
    │  
    ├─io_file
    │  │  imgread.py
    │  │  __init__.py
    │  │  
    │  ├─.ipynb_checkpoints
    │  └─__pycache__
    │          imgread.cpython-312.pyc
    │          __init__.cpython-312.pyc
    │          
    └─__pycache__
            __init__.cpython-312.pyc
            


In [1]:
import image.io_file.imgread
image.io_file.imgread.pngread()
image.io_file.imgread.jpgread()

pngread in ingread module
jpgread in imgread module


In [5]:
from image.io_file import imgread

imgread.pngread()
imgread.jpgread()

pngread in ingread module
jpgread in imgread module


In [9]:
from image.io_file.imgread import pngread

pngread()

pngread in ingread module


In [11]:
from image.io_file.imgread import *

pngread()
jpgread()

pngread in ingread module
jpgread in imgread module


In [13]:
import numpy as np 
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [15]:
data2 = [0.1,5,4,12,0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [17]:
a1.dtype

dtype('int64')

In [19]:
a2.dtype

dtype('float64')

In [21]:
np.array([0.5,2,0.01,8])

array([0.5 , 2.  , 0.01, 8.  ])

In [23]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [29]:
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [37]:
b2 = np.arange(5)
b2.shape

(5,)

In [39]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [43]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [49]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.array(['1.5','0.62','2','3.14','3.141595'])

array(['1.5', '0.62', '2', '3.14', '3.141595'], dtype='<U8')

In [55]:
str_a1 = np.array(['1.567','0.123','5.123','9','8'])

In [57]:
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [59]:
str_a1.dtype

dtype('<U5')

In [61]:
num_a1.dtype

dtype('float64')

In [63]:
str_a2 = np.array(['1','3','5','7','9'])

In [65]:
num_a2 = str_a2.astype(int)

In [67]:
num_a2

array([1, 3, 5, 7, 9])

In [69]:
str_a2.dtype

dtype('<U1')

In [71]:
num_a2.dtype

dtype('int64')

In [73]:
num_f1 = np.array([10,21,0.549,4.75,5.98])

In [75]:
num_i1 = num_f1.astype(int)

In [77]:
num_i1

array([10, 21,  0,  4,  5])

In [79]:
num_f1.dtype

dtype('float64')

In [81]:
num_i1.dtype

dtype('int64')

In [83]:
np.random.rand(2,3)

array([[0.50566135, 0.97686717, 0.66388549],
       [0.32912493, 0.60185871, 0.71885161]])

In [85]:
np.random.rand()

0.2969878588049817

In [87]:
np.random.rand(2,3,4)

array([[[0.44284277, 0.57749633, 0.17502357, 0.52820778],
        [0.8457516 , 0.27615544, 0.54821865, 0.574553  ],
        [0.15273973, 0.74736009, 0.60385266, 0.50439651]],

       [[0.65747047, 0.72965088, 0.97630498, 0.49665181],
        [0.15323619, 0.48522123, 0.02601388, 0.64037322],
        [0.04557065, 0.16881605, 0.71802295, 0.24420823]]])

In [89]:
np.random.randint(10, size=(3,4))

array([[8, 7, 6, 8],
       [5, 0, 5, 8],
       [0, 2, 2, 8]], dtype=int32)

In [91]:
np.random.randint(1,30)

1

In [93]:
arr1 = np.array([10,20,30,40])

In [95]:
arr2 = np.array([1,2,3,4])

In [97]:
arr1 + arr2

array([11, 22, 33, 44])

In [99]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [101]:
arr2 * 2

array([2, 4, 6, 8])

In [103]:
arr2 **2

array([ 1,  4,  9, 16])

In [105]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [107]:
arr1 / arr2

array([10., 10., 10., 10.])

In [109]:
arr1 / (arr2**2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [111]:
arr1 > 20

array([False, False,  True,  True])

In [113]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [115]:
arr3.sum(), arr3.mean()

(np.int64(10), np.float64(2.0))

In [117]:
[arr3.std(), arr3.var()]

[np.float64(1.4142135623730951), np.float64(2.0)]

In [119]:
[arr3.min(), arr3.max()]

[np.int64(0), np.int64(4)]

In [121]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [123]:
arr4.cumsum()

array([ 1,  3,  6, 10])

In [125]:
arr4.cumprod()

array([ 1,  2,  6, 24])

In [127]:
A = np.array([0,1,2,3]).reshape(2,2)

In [129]:
A

array([[0, 1],
       [2, 3]])

In [131]:
B = np.array([3,2,0,1]).reshape(2,2)

In [133]:
B

array([[3, 2],
       [0, 1]])

In [135]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [137]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [139]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [141]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [145]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [147]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [149]:
np.linalg.det(A)

np.float64(-2.0)

In [151]:
a1 = np.array([0,10,20,30,40,50])

In [153]:
a1

array([ 0, 10, 20, 30, 40, 50])

In [155]:
a1[0]

np.int64(0)

In [157]:
a1[4]

np.int64(40)

In [159]:
a1[5] = 70

In [161]:
a1

array([ 0, 10, 20, 30, 40, 70])

In [163]:
a1[[1,3,4]]

array([10, 30, 40])

In [165]:
a2 = np.arange(10,100,10).reshape(3,3)

In [167]:
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [169]:
a2[0,2]

np.int64(30)

In [171]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [173]:
a2[1]

array([40, 50, 60])

In [175]:
a2[1] = np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [177]:
a2[1] = [47,57,67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [179]:
a2[[0,2],[0,1]]

array([10, 80])

In [181]:
a = np.array([1,2,3,4,5,6])

In [183]:
a[a>3]

array([4, 5, 6])

In [185]:
a[(a%2)==0]

array([2, 4, 6])

In [187]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [189]:
b1[:3]

array([ 0, 10, 20])

In [191]:
b1[2:]

array([20, 30, 40, 50])

In [193]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [195]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [197]:
b2 = np.arange(10, 100, 10).reshape(3,3)

In [199]:
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [201]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [203]:
b2[:3,1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [205]:
b2[1][0:2]

array([40, 50])

In [211]:
b2[0:2, 1:3] = np.array([[25,35],[55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

In [7]:
import pandas as pd

In [9]:
s1 = pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [11]:
s1.index
print(s1.index)

RangeIndex(start=0, stop=5, step=1)


In [13]:
s1.values

array([10, 20, 30, 40, 50])

In [15]:
s2 = pd.Series(['a','b','c',1,2,3])
s2

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

In [17]:
import numpy as np

In [19]:
s3 = pd.Series([np.nan, 10, 30])
s3

0     NaN
1    10.0
2    30.0
dtype: float64

In [25]:
index_date = ['2018-10-07','2018-10-08','2018-10-09','2018-10-10']
s4 = pd.Series([200,195,np.nan, 205], index = index_date)
s4

2018-10-07    200.0
2018-10-08    195.0
2018-10-09      NaN
2018-10-10    205.0
dtype: float64

In [27]:
s5 = pd.Series({'국어':100,'영어':95,'수학':90})
s5

국어    100
영어     95
수학     90
dtype: int64

In [31]:
import pandas as pd 
pd.date_range(start='2019-01-01',end='2019-01-07')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [33]:
pd.date_range(start='2019/01/01',end='2019.01.07')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [35]:
pd.date_range(start='01-01-2019',end='01/07/2019')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [39]:
pd.date_range(start='2019-01-01',periods=7)

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [41]:
pd.date_range(start='2019-01-01',periods = 4, freq = '2D')

DatetimeIndex(['2019-01-01', '2019-01-03', '2019-01-05', '2019-01-07'], dtype='datetime64[ns]', freq='2D')

In [43]:
pd.date_range(start='2019-01-01',periods = 4, freq = 'W')

DatetimeIndex(['2019-01-06', '2019-01-13', '2019-01-20', '2019-01-27'], dtype='datetime64[ns]', freq='W-SUN')

In [45]:
pd.date_range(start='2019-01-01',periods = 12, freq = '2BM')

C:\Users\user1\AppData\Local\Temp\ipykernel_12032\824770337.py:1: FutureWarning: 'BM' is deprecated and will be removed in a future version, please use 'BME' instead.
  pd.date_range(start='2019-01-01',periods = 12, freq = '2BM')


DatetimeIndex(['2019-01-31', '2019-03-29', '2019-05-31', '2019-07-31',
               '2019-09-30', '2019-11-29', '2020-01-31', '2020-03-31',
               '2020-05-29', '2020-07-31', '2020-09-30', '2020-11-30'],
              dtype='datetime64[ns]', freq='2BME')

In [47]:
pd.date_range(start='2019-01-01',periods = 4 , freq = 'QS')

DatetimeIndex(['2019-01-01', '2019-04-01', '2019-07-01', '2019-10-01'], dtype='datetime64[ns]', freq='QS-JAN')

In [49]:
pd.date_range(start='2019-01-01',periods = 3, freq = 'AS')

C:\Users\user1\AppData\Local\Temp\ipykernel_12032\3748707511.py:1: FutureWarning: 'AS' is deprecated and will be removed in a future version, please use 'YS' instead.
  pd.date_range(start='2019-01-01',periods = 3, freq = 'AS')


DatetimeIndex(['2019-01-01', '2020-01-01', '2021-01-01'], dtype='datetime64[ns]', freq='YS-JAN')

In [51]:
pd.date_range(start = '2019-01-01 08:00',periods = 10, freq = 'H')

C:\Users\user1\AppData\Local\Temp\ipykernel_12032\1190856521.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.date_range(start = '2019-01-01 08:00',periods = 10, freq = 'H')


DatetimeIndex(['2019-01-01 08:00:00', '2019-01-01 09:00:00',
               '2019-01-01 10:00:00', '2019-01-01 11:00:00',
               '2019-01-01 12:00:00', '2019-01-01 13:00:00',
               '2019-01-01 14:00:00', '2019-01-01 15:00:00',
               '2019-01-01 16:00:00', '2019-01-01 17:00:00'],
              dtype='datetime64[ns]', freq='h')

In [53]:
pd.date_range(start = '2019-01-01 08:00', periods = 10 , freq = 'BH')

C:\Users\user1\AppData\Local\Temp\ipykernel_12032\2358304759.py:1: FutureWarning: 'BH' is deprecated and will be removed in a future version, please use 'bh' instead.
  pd.date_range(start = '2019-01-01 08:00', periods = 10 , freq = 'BH')


DatetimeIndex(['2019-01-01 09:00:00', '2019-01-01 10:00:00',
               '2019-01-01 11:00:00', '2019-01-01 12:00:00',
               '2019-01-01 13:00:00', '2019-01-01 14:00:00',
               '2019-01-01 15:00:00', '2019-01-01 16:00:00',
               '2019-01-02 09:00:00', '2019-01-02 10:00:00'],
              dtype='datetime64[ns]', freq='bh')

In [55]:
pd.date_range(start = '2019-01-01 10:00', periods = 4, freq = '30min')

DatetimeIndex(['2019-01-01 10:00:00', '2019-01-01 10:30:00',
               '2019-01-01 11:00:00', '2019-01-01 11:30:00'],
              dtype='datetime64[ns]', freq='30min')

In [57]:
pd.date_range(start = '2019-01-01 10:00, periods = 4, freq = '30T')

SyntaxError: invalid decimal literal (344492982.py, line 1)

In [59]:
pd.date_range(start = '2019-01-01 10:00:00', periods = 4, freq = '10S')

C:\Users\user1\AppData\Local\Temp\ipykernel_12032\3026018592.py:1: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
  pd.date_range(start = '2019-01-01 10:00:00', periods = 4, freq = '10S')


DatetimeIndex(['2019-01-01 10:00:00', '2019-01-01 10:00:10',
               '2019-01-01 10:00:20', '2019-01-01 10:00:30'],
              dtype='datetime64[ns]', freq='10s')

In [61]:
index_date = pd.date_range(start = '2019-03-01',periods = 5, freq = 'D')
pd.Series([51,62,55,49,58],index = index_date)

2019-03-01    51
2019-03-02    62
2019-03-03    55
2019-03-04    49
2019-03-05    58
Freq: D, dtype: int64

In [63]:
# DataFrame()의 인자인 data에는 리스트와 형태가 유사한 데이터 타입은 모두 사용할수 있습니다. 즉 , 
# 리스트와 딕셔너리 타입의 데이터, Numpy 의 배열 데이터, Series 나 DataFrame 타입의 데이터를 입력할수있습니다. 
# df = pd.DataFrame(data [, index = index_data, columns = columns_data])

import pandas as pd 

pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [65]:
import numpy as np
import pandas as pd 

data_list = np.array([[10,20,30],[40,50,60],[70,80,90]])
pd.DataFrame(data_list)

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [71]:
import numpy as np 
import pandas as pd
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
index_date = pd.date_range('2019-09-01',periods = 4)
columns_list=['A','B','C']
pd.DataFrame(data,index = index_date, columns = columns_list)

A   B   C
2019-09-01   1   2   3
2019-09-02   4   5   6
2019-09-03   7   8   9
2019-09-04  10  11  12

In [73]:
table_data = {'연도':[2015,2016,2016,2017,2017],'지사':['한국','한국','미국','한국','미국'],'고객 수':[200,250,450,300,500]}
table_data

{'연도': [2015, 2016, 2016, 2017, 2017],
 '지사': ['한국', '한국', '미국', '한국', '미국'],
 '고객 수': [200, 250, 450, 300, 500]}

In [75]:
pd.DataFrame(table_data)

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2016  미국   450
3  2017  한국   300
4  2017  미국   500

In [79]:
df = pd.DataFrame(table_data, columns = ['연도','지사','고객 수'])
df

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2016  미국   450
3  2017  한국   300
4  2017  미국   500

In [81]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [83]:
df.columns

Index(['연도', '지사', '고객 수'], dtype='object')

In [85]:
df.values

array([[2015, '한국', 200],
       [2016, '한국', 250],
       [2016, '미국', 450],
       [2017, '한국', 300],
       [2017, '미국', 500]], dtype=object)

In [87]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])
s1 + s2

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [89]:
s1 * s2

0     10
1     40
2     90
3    160
4    250
dtype: int64

In [91]:
s2 /s1

0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
dtype: float64

In [93]:
s3  = pd.Series([1,2,3,4])
s4 = pd.Series([10,20,30,40,50])
s3 + s4

0    11.0
1    22.0
2    33.0
3    44.0
4     NaN
dtype: float64

In [95]:
s4 - s3

0     9.0
1    18.0
2    27.0
3    36.0
4     NaN
dtype: float64

In [97]:
s3 * s4

0     10.0
1     40.0
2     90.0
3    160.0
4      NaN
dtype: float64

In [99]:
s4/ s3

0    10.0
1    10.0
2    10.0
3    10.0
4     NaN
dtype: float64

In [101]:
table_data1 = {'A':[1,2,3,4,5],'B':[10,20,30,40,50],'C':[100,200,300,400,500]}
df1 = pd.DataFrame(table_data1)
df1


A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [103]:
table_data2 = {'A':[6,7,8],'B':[60,70,80],'C':[600,700,800]}
df2 = pd.DataFrame(table_data2)
df2

A   B    C
0  6  60  600
1  7  70  700
2  8  80  800

In [105]:
df1 + df2

A      B       C
0   7.0   70.0   700.0
1   9.0   90.0   900.0
2  11.0  110.0  1100.0
3   NaN    NaN     NaN
4   NaN    NaN     NaN

In [109]:
table_data3= {'봄':[256.5,264.3,215.9,223.2,312.8],'여름':[770.6,567.5,599.8,387.1,446.2],'가을':[363.5,231.2,293.1,247.7,381.6],'겨울':[139.3,59.9,76.9,109.1,108.1]}
columns_list =['봄','여름','가을','겨울']
index_list =['2012','2013','2014','2015','2016']

df3 = pd.DataFrame(table_data3, columns = columns_list, index = index_list)
df3

봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [111]:
df3.mean()

봄     254.54
여름    554.24
가을    303.42
겨울     98.66
dtype: float64

In [113]:
df3.std()

봄      38.628267
여름    148.888895
가을     67.358496
겨울     30.925523
dtype: float64

In [115]:
df3.mean(axis=1)

2012    382.475
2013    280.725
2014    296.425
2015    241.775
2016    312.175
dtype: float64

In [117]:
df3.std(axis=1)

2012    274.472128
2013    211.128782
2014    221.150739
2015    114.166760
2016    146.548658
dtype: float64

In [119]:
df3.describe()

봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.800000  770.600000  381.600000  139.300000

In [121]:
import pandas as pd 
import numpy as np
KTX_data = {'경부선 KTX':[39060,39896,42005,43621,41702,41266,32427],
            '호남선 KTX':[7313,6967,6873,6626,8675,10622,9228],
            '경전선 KTX':[3627,4168,4088,4424,4606,4984,5570],
            '전라선 KTX':[309,1771,1954,2244,3146,3945,5766],
            '동해선 KTX':[np.nan,np.nan,np.nan,np.nan,2395,3786,6667]}
col_list = ['경부선 KTX','호남선 KTX','경전선 KTX','전라선 KTX','동해선 KTX']
index_list = ['2011','2012','2013','2014','2015','2016','2017']

df_KTX = pd.DataFrame(KTX_data, columns = col_list, index= index_list)
df_KTX

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [123]:
df_KTX.index

Index(['2011', '2012', '2013', '2014', '2015', '2016', '2017'], dtype='object')

In [125]:
df_KTX.columns

Index(['경부선 KTX', '호남선 KTX', '경전선 KTX', '전라선 KTX', '동해선 KTX'], dtype='object')

In [127]:
df_KTX.values

array([[39060.,  7313.,  3627.,   309.,    nan],
       [39896.,  6967.,  4168.,  1771.,    nan],
       [42005.,  6873.,  4088.,  1954.,    nan],
       [43621.,  6626.,  4424.,  2244.,    nan],
       [41702.,  8675.,  4606.,  3146.,  2395.],
       [41266., 10622.,  4984.,  3945.,  3786.],
       [32427.,  9228.,  5570.,  5766.,  6667.]])

In [129]:
df_KTX.head()


경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0

In [131]:
df_KTX.tail()

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [133]:
df_KTX.head(3)

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN

In [135]:
df_KTX.tail(2)


경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [137]:
df_KTX[1:2]

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2012    39896     6967     4168     1771      NaN

In [139]:
df_KTX[2:5]

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0